.flake8, .github/workflows/ci.yml, CHANGELOG.md, README.md, beaker/__init__.py, beaker/client.py, beaker/config.py, beaker/exceptions.py, docs/source/api.rst, requirements.txt, scripts/hello_world.py, tests/client_test.py, tests/hello_test.py
=> API improvements

CHANGELOG.md, beaker/config.py
=> fix crash when home dir missing

CHANGELOG.md, beaker/client.py
=> initialize Docker client lazily

CHANGELOG.md, beaker/__init__.py, beaker/client.py, conftest.py
=> add Beaker.experiment.await_all() and .delete()

CHANGELOG.md, beaker/__init__.py, beaker/client.py, beaker/data_model.py, beaker/exceptions.py, beaker/util.py
=> Support directories with `Beaker.dataset.create()`

CHANGELOG.md, beaker/__init__.py, beaker/client.py, beaker/conftest.py, beaker/data_model.py, beaker/exceptions.py, beaker/services/__init__.py, beaker/services/cluster.py, beaker/services/experiment.py, beaker/services/job.py, beaker/services/node.py, conftest.py, docs/source/api.rst, tests/experiment_test.py, tests/job_test.py, tests/node_test.py
=> Add `Beaker.cluster.utilization()` method

CHANGELOG.md, beaker/data_model/cluster.py
=> Rename `Cluster.nodeCost` to `Cluster.node_cost`

.github/workflows/main.yml, dev-requirements.txt, docs/source/conf.py, docs/source/examples.md, docs/source/index.rst, examples/sweep/.dockerignore, examples/sweep/Dockerfile, examples/sweep/README.md, examples/sweep/entrypoint.py, examples/sweep/run.py
=> Sweep example

CHANGELOG.md, beaker/data_model/job.py, beaker/exceptions.py, beaker/services/experiment.py, beaker/services/job.py, docs/source/faq.md
=> Additions to `Beaker.experiment` and `Beaker.job`

beaker/__init__.py, beaker/client.py, conftest.py, tests/workspace_test.py
Fixes #108 
- Updates workspace / experiment / image fixtures to public versions so anyone should be able to run *most* tests locally without any trouble.
=> Update workspace fixtures

CHANGELOG.md, beaker/services/experiment.py, beaker/services/job.py, beaker/util.py, conftest.py, tests/job_test.py
=> Add `since` parameter to `.logs()` methods

CHANGELOG.md, beaker/exceptions.py, beaker/services/experiment.py
Fixes the other issue mentioned in
https://github.com/allenai/tango/issues/385#issuecomment-1238523405
=> Catch tasks that are stopped before job created

CHANGELOG.md, beaker/client.py, beaker/exceptions.py, beaker/services/account.py, beaker/services/cluster.py, beaker/services/dataset.py, beaker/services/experiment.py, beaker/services/group.py, beaker/services/image.py, beaker/services/job.py, beaker/services/node.py, beaker/services/organization.py, beaker/services/secret.py, beaker/services/service_client.py, beaker/services/workspace.py, beaker/util.py, docs/source/api.rst
Fixes https://github.com/allenai/tango/issues/396, fixes https://github.com/allenai/tango/issues/394
=> Make client more robust to all types of recoverable errors

CHANGELOG.md, beaker/data_model/experiment_spec.py
- Adds a field for the new `constraints` task parameter.
=> Add `constraints` to TaskSpec

beaker/data_model/experiment_spec.py, beaker/exceptions.py, beaker/services/experiment.py, tests/data_model_test.py
=> Allow no beaker or docker image in exp spec

CHANGELOG.md, beaker/data_model/dataset.py, beaker/services/dataset.py, dev-requirements.txt, requirements.txt, tests/data_model_test.py
Followup to https://github.com/allenai/beaker/issues/2966
=> Get digest from `Beaker.dataset.ls()`

CHANGELOG.md, beaker/__init__.py, beaker/client.py, beaker/conftest.py, beaker/data_model/cluster.py, conftest.py, tests/cluster_test.py, tests/data_model_test.py
=> Add `Cluster.allow_preemptible_restriction_exceptions`

CHANGELOG.md, beaker/data_model/experiment_spec.py, beaker/util.py, tests/util_test.py
=> Allow human-readable duration strings

CHANGELOG.md, pyproject.toml
See https://github.com/docker/docker-py/issues/3256
=> update dependency pins to fix requests/docker-py issue

CHANGELOG.md, beaker/data_model/job.py, beaker/services/service_client.py
=> Add `Job.execution_results`

CHANGELOG.md
=> I think I didn't do Changelog.md correctly
